[workspace]
resolver = "2"
members = ["crates/elk-graph", "crates/elk-core", "crates/elk-cli", "crates/elk-alg-layered", "crates/elk-alg-common", "crates/elk-alg-force", "crates/elk-alg-radial", "crates/elk-alg-rectpacking", "crates/elk-alg-mrtree", "crates/elk-alg-topdownpacking", "crates/elk-alg-spore", "crates/elk-alg-disco"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["depetrol <depetrol03@gmail.com>"]
repository = "https://github.com/depetrol/elkrs"
homepage = "https://github.com/depetrol/elkrs"
readme = "README.md"
keywords = ["graph", "layout", "elk", "diagram", "layered"]
categories = ["algorithms", "mathematics", "visualization"]

[workspace.dependencies]
indexmap = "2"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order", "float_roundtrip"] }
