[workspace]
resolver = "2"
members = ["crates/elk-graph", "crates/elk-core", "crates/elk-cli", "crates/elk-alg-layered", "crates/elk-alg-common", "crates/elk-alg-force", "crates/elk-alg-radial", "crates/elk-alg-rectpacking", "crates/elk-alg-mrtree"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "EPL-2.0"

[workspace.dependencies]
indexmap = "2"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order", "float_roundtrip"] }
