[package]
name = "elk-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "elk_cli"
path = "src/lib.rs"

[[bin]]
name = "elkrs"
path = "src/main.rs"

[dependencies]
elk-alg-force = { path = "../elk-alg-force" }
elk-alg-layered = { path = "../elk-alg-layered" }
elk-alg-mrtree = { path = "../elk-alg-mrtree" }
elk-alg-radial = { path = "../elk-alg-radial" }
elk-alg-rectpacking = { path = "../elk-alg-rectpacking" }
elk-core = { path = "../elk-core" }
elk-graph = { path = "../elk-graph" }
serde_json.workspace = true
